### ISSUE TITLE
Microservice restarts due to undefined server

### ISSUE THREAD

**Issue by EnFinlay** [Retsly/microservice#32]
First reported here: https://github.com/Retsly/pdfd/issues/8, but later seen on `xlmd`. 

Error logs:
```
[PM2] Tailing last 80 lines for [pdfd] process

pdfd-163 (err): TypeError: Cannot read property 'server' of undefined
pdfd-163 (err):     at MicroServiceServer.onMessage (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/lib/server.js:67:16)
pdfd-163 (err):     at RepSocket.<anonymous> (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/lib/server.js:31:20)
pdfd-163 (err):     at emitNone (events.js:67:13)
pdfd-163 (err):     at RepSocket.emit (events.js:166:7)
pdfd-163 (err):     at Parser.<anonymous> (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/lib/sockets/rep.js:65:15)
pdfd-163 (err):     at emitOne (events.js:77:13)
pdfd-163 (err):     at Parser.emit (events.js:169:7)
pdfd-163 (err):     at Parser._write (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/node_modules/amp/lib/stream.js:91:16)
pdfd-163 (err):     at doWrite (_stream_writable.js:292:12)
pdfd-163 (err):     at writeOrBuffer (_stream_writable.js:278:5)
pdfd-163 (err): TypeError: Cannot read property 'server' of undefined
pdfd-163 (err):     at MicroServiceServer.onMessage (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/lib/server.js:67:16)
pdfd-163 (err):     at RepSocket.<anonymous> (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/lib/server.js:31:20)
pdfd-163 (err):     at emitNone (events.js:67:13)
pdfd-163 (err):     at RepSocket.emit (events.js:166:7)
pdfd-163 (err):     at Parser.<anonymous> (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/lib/sockets/rep.js:65:15)
pdfd-163 (err):     at emitOne (events.js:77:13)
pdfd-163 (err):     at Parser.emit (events.js:169:7)
pdfd-163 (err):     at Parser._write (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/node_modules/amp/lib/stream.js:91:16)
pdfd-163 (err):     at doWrite (_stream_writable.js:292:12)
pdfd-163 (err):     at writeOrBuffer (_stream_writable.js:278:5)
pdfd-163 (err): TypeError: Cannot read property 'server' of undefined
pdfd-163 (err):     at MicroServiceServer.onMessage (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/lib/server.js:67:16)
pdfd-163 (err):     at RepSocket.<anonymous> (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/lib/server.js:31:20)
pdfd-163 (err):     at emitNone (events.js:67:13)
pdfd-163 (err):     at RepSocket.emit (events.js:166:7)
pdfd-163 (err):     at Parser.<anonymous> (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/lib/sockets/rep.js:65:15)
pdfd-163 (err):     at emitOne (events.js:77:13)
pdfd-163 (err):     at Parser.emit (events.js:169:7)
pdfd-163 (err):     at Parser._write (/home/ubuntu/retsly-architecture/microservices/pdfd/node_modules/@retsly/microservice/node_modules/amp/lib/stream.js:91:16)
pdfd-163 (err):     at doWrite (_stream_writable.js:292:12)
pdfd-163 (err):     at writeOrBuffer (_stream_writable.js:278:5)
```

**Comment by MadManMathew** [comment]
@EnFinlay did you fix this? it appears you did

**Comment by EnFinlay** [comment]
@MadManMathew I never actively fixed it.  It was intermittent issue so there's a chance recent changes fixed it, but I wouldn't put money on it.

**Comment by MadManMathew** [comment]
@EnFinlay I looks like you fixed the type error, but I guess there could be a larger problem at hand.

**Comment by EnFinlay** [comment]
@MadManMathew the fix I put in was for the case where an HTTP/TCP socket is opened "outside" the `microservice` system (a malicious hook inside our firewall).  This issue involves a proper invocation of the `microservice`, but for some reason the server isn't defined.  At least that's how I understand it.

**Comment by RongxinZhang** [comment]
@MadManMathew @EnFinlay how can we check this?

**Comment by EnFinlay** [comment]
@RongxinZhang I don't think we can.  I say we close the issue and re-open if we see it again.

**Comment by RongxinZhang** [comment]
@EnFinlay @MadManMathew  sounds good.
